/*
 * File: app/view/MainPanelViewModel.js
 * Date: Tue Sep 14 2021 11:56:02 GMT-0500 (Central Daylight Time)
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BetterOinSearch.view.MainPanelViewModel', {
	extend: 'Ext.app.ViewModel',
	alias: 'viewmodel.mainpanel',

	requires: [
		'Ext.data.Store',
		'Ext.data.field.Integer',
		'Ext.data.proxy.Ajax',
		'Ext.data.reader.Array',
		'Ext.util.Sorter'
	],

	stores: {
		oinAppStore: {
			fields: [
				{
					name: 'Name'
				},
				{
					name: 'DisplayName',
					sortType: 'asUCString'
				},
				{
					name: 'Website'
				},
				{
					name: 'LogoImage'
				},
				{
					name: 'Description'
				},
				{
					name: 'AppCategory'
				},
				{
					name: 'AppCategoryLabel'
				},
				{
					name: 'Custom'
				},
				{
					name: 'SecurePasswordStore'
				},
				{
					name: 'SAML_2_0'
				},
				{
					name: 'SAML_1_1'
				},
				{
					name: 'BookMark'
				},
				{
					name: 'BrowserPlugin'
				},
				{
					name: 'AutoLogin'
				},
				{
					name: 'BasicAuth'
				},
				{
					name: 'ImportNewUsers'
				},
				{
					name: 'ImportProfileUpdates'
				},
				{
					name: 'PushNewUsers'
				},
				{
					name: 'PushProfileUpdates'
				},
				{
					name: 'PushUserDeactivation'
				},
				{
					name: 'PushPasswordUpdates'
				},
				{
					name: 'ReactivateUsers'
				},
				{
					name: 'AutoConfirmImports'
				},
				{
					type: 'int',
					name: 'Ranking'
				},
				{
					name: 'OMM'
				},
				{
					name: 'Version'
				}
			],
			proxy: {
				type: 'ajax',
				url: '/BetterOinSearch/oin.json',
				reader: {
					type: 'array'
				}
			}
		},
		myApps: {
			fields: [
				{
					name: 'Name'
				},
				{
					name: 'DisplayName'
				},
				{
					name: 'Website'
				},
				{
					name: 'LogoImage'
				},
				{
					name: 'Description'
				},
				{
					name: 'AppCategory'
				},
				{
					name: 'AppCategoryLabel'
				},
				{
					name: 'Custom'
				},
				{
					name: 'SecurePasswordStore'
				},
				{
					name: 'SAML_2_0'
				},
				{
					name: 'SAML_1_1'
				},
				{
					name: 'BookMark'
				},
				{
					name: 'BrowserPlugin'
				},
				{
					name: 'AutoLogin'
				},
				{
					name: 'BasicAuth'
				},
				{
					name: 'ImportNewUsers'
				},
				{
					name: 'ImportProfileUpdates'
				},
				{
					name: 'PushNewUsers'
				},
				{
					name: 'PushProfileUpdates'
				},
				{
					name: 'PushUserDeactivation'
				},
				{
					name: 'PushPasswordUpdates'
				},
				{
					name: 'ReactivateUsers'
				},
				{
					name: 'AutoConfirmImports'
				},
				{
					name: 'Ranking'
				},
				{
					name: 'OMM'
				},
				{
					name: 'Version'
				}
			]
		},
		oinCategoryStore: {
			fields: [
				{
					name: 'category'
				},
				{
					name: 'categoryLabel'
				},
				{
					name: 'count'
				}
			],
			sorters: {
				direction: 'DESC',
				property: 'count'
			}
		},
		oinCapabilities: {
			data: [
				[
					'SSO - SAML'
				],
				[
					'SSO - OIDC'
				],
				[
					'SSO - WS-Federation'
				],
				[
					'Provisioning'
				],
				[
					'Workflows'
				]
			],
			fields: [
				{
					name: 'capabilities'
				}
			]
		}
	}

});