/*
 * File: app/view/WorkflowsPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BetterOinSearch.view.WorkflowsPanel', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.workflowspanel',

	requires: [
		'BetterOinSearch.view.WorkflowsPanelViewModel',
		'Ext.XTemplate'
	],

	config: {
		autoScroll: true
	},

	viewModel: {
		type: 'workflowspanel'
	},
	frame: true,
	resizable: true,
	resizeHandles: 'w',
	tpl: [
		'<tpl if="values.templates.length &gt; 0">',
		'	<h2><U>Templates:</U></h2>',
		'</tpl>',
		'<tpl for="templates">',
		'	<p><B>{title}</B> - {description}</p>',
		'</tpl>',
		'',
		'<tpl if="values.events.length &gt; 0">',
		'	<h2><U>Events:</U></h2>',
		'</tpl>',
		'<tpl for="events">',
		'	<p><B>{displayname}</B> - {description}</p>',
		'</tpl>',
		'',
		'<tpl if="values.actions.length &gt; 0">',
		'	<h2><U>Actions:</U></h2>',
		'</tpl>',
		'<tpl for="actions">',
		'	<p><B>{displayname}</B> - {description}</p>',
		'</tpl>'
	],
	width: 275,
	animCollapse: 0,
	bodyBorder: true,
	bodyPadding: 6,
	collapsed: true,
	collapseDirection: 'right',
	collapsible: true,
	title: 'Workflows',
	titleCollapse: true

});